#ifndef __PRINTF_IMPL_LL_
#define __PRINTF_IMPL_LL_

#include "main.h"

#define PRINTF_UART_INSTANCE					USART2
#define PRINTF_UART_BAUDRATE					921600
#define PRINTF_UART_WORDLENGTH 					UART_WORDLENGTH_8B
#define PRINTF_UART_PARITY 						UART_PARITY_NONE
#define PRINTF_UART_STOPBITS 					UART_STOPBITS_1
#define PRINTF_UART_CLOCK_ENABLE 				__USART2_CLK_ENABLE
#define PRINTF_UART_CLOCK_DISABLE 				__USART2_CLK_DISABLE

#define PRINTF_UART_RX_GPIO_PIN					GPIO_PIN_15
#define PRINTF_UART_RX_GPIO_PORT				GPIOA
#define PRINTF_UART_RX_GPIO_ALTERNATE			GPIO_AF7_USART2
#define PRINTF_UART_RX_GPIO_CLOCK_ENABLE		__GPIOA_CLK_ENABLE
#define PRINTF_UART_RX_GPIO_CLOCK_DISABLE		__GPIOA_CLK_DISABLE

#define PRINTF_UART_TX_GPIO_PIN					GPIO_PIN_2
#define PRINTF_UART_TX_GPIO_PORT				GPIOA
#define PRINTF_UART_TX_GPIO_ALTERNATE			GPIO_AF7_USART2
#define PRINTF_UART_TX_GPIO_CLOCK_ENABLE		__GPIOA_CLK_ENABLE
#define PRINTF_UART_TX_GPIO_CLOCK_DISABLE		__GPIOA_CLK_DISABLE

#endif
